#ifndef HK_NFCERR_H
#define HK_NFCERR_H
/*
 * Copyright (c) 2012-2012, hiro99ma(uenokuma@gmail.com)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice,
 *         this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice,
 *         this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 */

/// @def HKNFCERR_NONE
#define HKNFCERR_NONE				(0)

/// @def HKNFCERR_OPEN
#define HKNFCERR_ALREADY_OPEN		(1)
#define HKNFCERR_LOWLEVEL_OPEN		(2)

#define HKNFCERR_PCD				(0x10)
#define HKNFCERR_PCD_INIT			(HKNFCERR_PCD+0)
#define HKNFCERR_PCD_CFG			(HKNFCERR_PCD+1)
#define HKNFCERR_PCD_RESET			(HKNFCERR_PCD+2)
#define HKNFCERR_PCD_DIAG			(HKNFCERR_PCD+3)
#define HKNFCERR_PCD_SETP			(HKNFCERR_PCD+4)
#define HKNFCERR_PCD_WRITEREG		(HKNFCERR_PCD+5)
#define HKNFCERR_PCD_GETFW			(HKNFCERR_PCD+6)
#define HKNFCERR_PCD_GETSTAT		(HKNFCERR_PCD+7)
#define HKNFCERR_PCD_COMMTHRUEX		(HKNFCERR_PCD+8)
#define HKNFCERR_PCD_INJUMP			(HKNFCERR_PCD+9)
#define HKNFCERR_PCD_INDTEX			(HKNFCERR_PCD+10)
#define HKNFCERR_PCD_INPSV			(HKNFCERR_PCD+11)
#define HKNFCERR_PCD_INCOMMTHRU		(HKNFCERR_PCD+12)
#define HKNFCERR_PCD_INREL			(HKNFCERR_PCD+13)
#define HKNFCERR_PCD_TGINIT			(HKNFCERR_PCD+14)
#define HKNFCERR_PCD_TGSETGB		(HKNFCERR_PCD+15)
#define HKNFCERR_PCD_TGGETDT		(HKNFCERR_PCD+16)
#define HKNFCERR_PCD_TGSETDT		(HKNFCERR_PCD+17)
#define HKNFCERR_PCD_TGRES			(HKNFCERR_PCD+18)
#define HKNFCERR_PCD_TGGETINI		(HKNFCERR_PCD+19)
#define HKNFCERR_PCD_POWERDOWN		(HKNFCERR_PCD+20)


#define HKNFCERR_LLCP				(0x30)
#define HKNFCERR_LLCP_START			(HKNFCERR_LLCP+0)
#define HKNFCERR_LLCP_ADDDT			(HKNFCERR_LLCP+1)
#define HKNFCERR_LLCP_CONN			(HKNFCERR_LLCP+2)
#define HKNFCERR_LLCP_TIMEOUT		(HKNFCERR_LLCP+3)
#define HKNFCERR_LLCP_ERR			(HKNFCERR_LLCP+4)


#define HKNFCERR_SNEP				(0x40)
#define HKNFCERR_SNEP_NOTSUP		(HKNFCERR_SNEP+0)
#define HKNFCERR_SNEP_PUT			(HKNFCERR_SNEP+1)
#define HKNFCERR_SNEP_ERR			(HKNFCERR_SNEP+2)


#define HKNFCERR_			()
#define HKNFCERR_			()
#define HKNFCERR_			()
#define HKNFCERR_			()
#define HKNFCERR_			()
#define HKNFCERR_			()


#endif /* HK_NFCERR_H */
